### ISSUE TITLE
A bunch of errors while trying to run threader.py

### ISSUE THREAD

**Issue by nirzaa** [dievus/threader3000#14]
The script has been working for me for a long time, but since downloaded it again recently it gives me many errors while trying to run it.
Is it just me or a bug in the script?

Thank you

**Comment by dievus** [comment]
Really isn't helpful if you don't include what the errors are, what you are trying to do, etc.

I just downloaded it to a fresh Ubuntu 20.04 machine with Python3.8 and it works just fine.

**Comment by nirzaa** [comment]
I'm getting `OSError: [Errno 24] Too many open files` type of error. The log file itself is quite large with many details.
I thought maybe email it to use by an `.txt` file, but while looking for your mail I'm getting: `dievus@users.noreply.github.com`

**Comment by dievus** [comment]
You can try changing line 73 to 200 instead of 1500. It's likely a local resource error with the increase in thread count that I recently added.

**Comment by nirzaa** [comment]
Great, thank you

**Comment by dievus** [comment]
See https://github.com/dievus/threader3000/issues/14

Closing as it's already been reported. In the end, it is an issue with your resources.
